package br.com.joaoflach.subnautica.models;

public enum Biome {
    NONE,KELP_FOREST,GRASSY_PLATEAUS,UNDERWATER_ISLANDS,MUSHROOM_FOREST,KOOSH_ZONE,CRASH_ZONE,FLOATING_ISLANDS,GRAND_REEF,SPARSE_REEF,BLOOD_KELP,DUNES,INACTIVE_LAVA_ZONES,DEADZONE
}
